/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'excerpt' : IDL.Text,
  'imageId' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Collection = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageId' : IDL.Text,
});
export const Category = IDL.Variant({
  'hair' : IDL.Null,
  'gifts' : IDL.Null,
  'wellness' : IDL.Null,
  'skincare' : IDL.Null,
  'makeup' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Float64,
  'imageId' : IDL.Text,
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getBlogPostCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], []),
  'getCollectionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getProductsByCategoryText' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], []),
  'hasInCart' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'hasInWishlist' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'excerpt' : IDL.Text,
    'imageId' : IDL.Text,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Collection = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageId' : IDL.Text,
  });
  const Category = IDL.Variant({
    'hair' : IDL.Null,
    'gifts' : IDL.Null,
    'wellness' : IDL.Null,
    'skincare' : IDL.Null,
    'makeup' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Float64,
    'imageId' : IDL.Text,
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getBlogPostCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], []),
    'getCollectionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByCategoryText' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], []),
    'hasInCart' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'hasInWishlist' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };